name: main ci
on:
  push:
    branches:
      - main
jobs:
  ios:
    name: flutter ios build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build ipa
      - run: mkdir Payload
      - run: mv build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app ./Payload
      - run: zip -r Payload.zip Payload
      - run: mv Payload.zip louZero.ipa
      - uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
        with:
          appId: ${{secrets.FIREBASE_APPLE_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: louZero.ipa
      - uses: actions/upload-artifact@v2
        with:
          name: louZero.ipa
          path: |
            louZero.ipa
  android:
    name: flutter apk build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
    - run: flutter build apk --release
    - uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        file: build/app/outputs/flutter-apk/app-release.apk
    - uses: actions/upload-artifact@v2
      with:
        name: louZero.apk
        path: |
          build/app/outputs/flutter-apk/app-release.apk